[build]
publish = "public"
command = "yarn project-setup; yarn build"

[build.environment]
HUGO_VERSION = "0.124.1"
GO_VERSION = "1.22.2"

# add redirect home-->blog
[[redirects]]
from = '/'
to = '/blog/'
status = 301 
force = true # always redirect
