# defaultContentLanguageInSubdir must be true for this to work.

# Other languages redirects
# [[redirects]]
# from = '/fr/**'
# to = '/fr/404.html'
# status = 404

# Default language must be last.
[[redirects]]
from = '/**'
to = '/en/404.html'
status = 404

# Direct home (/) to blog posts page
[[redirects]]
from = '/'
to = '/blog/'
status = 301 
force = true # always redirect


