# defaultContentLanguageInSubdir must be true for this to work.

# Other languages redirects
# [[redirects]]
# from = '/fr/**'
# to = '/fr/404.html'
# status = 404

# Default home page to blog posts
[[redirects]]
from = '/'
to = '/blog/'
status = 301  # Using 301 for permanent redirect

# Default language must be last.
[[redirects]]
from = '/**'
to = '/en/404.html'
status = 404

